/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.*;
import javax.swing.JOptionPane;
import BaseDatos.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
/**
 *
 * @author Admin
 */
public class DepositoFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DepositoFrame.class.getName());

    /**
     * Creates new form DepositoFrame
     */
    private Banco banco;
    private Usuario usuario;

    public DepositoFrame(Banco banco, Usuario usuario) {
        initComponents();
        this.banco = banco;
        this.usuario = usuario;
        this.setTitle("Deposito");

        // Si el usuario es cliente, podríamos pre-llenar su cuenta automáticamente
        if (usuario instanceof UsuarioCliente) {
            UsuarioCliente uc = (UsuarioCliente) usuario;
            // Aquí podrías buscar la primera cuenta del cliente y ponerla en txtCuenta
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        txtCuenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(239, 184, 16));
        jButton1.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Realizar Depósito");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Monto a depositar:");

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cuenta Destino:");

        txtMonto.setBackground(new java.awt.Color(204, 204, 204));
        txtMonto.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(0, 0, 0));
        txtMonto.addActionListener(this::txtMontoActionPerformed);

        txtCuenta.setBackground(new java.awt.Color(204, 204, 204));
        txtCuenta.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        txtCuenta.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(10, 10, 10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String codigoCuenta = txtCuenta.getText().trim();
            String montoTxt = txtMonto.getText().trim();

            if (codigoCuenta.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese una cuenta.");
                return;
            }
            if (montoTxt.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un monto.");
                return;
            }

            double monto = Double.parseDouble(montoTxt);

            // Abrir conexión
            try (Connection conn = Conexion.conectar()) {
                if (conn == null) {
                    JOptionPane.showMessageDialog(this, "Error al conectar a la base de datos.");
                    return;
                }

                // 1. Validar que la cuenta exista
                Cuenta cta = CuentaDAO.obtenerCuenta(conn, codigoCuenta);
                if (cta == null) {
                    JOptionPane.showMessageDialog(this, "La cuenta no existe.");
                    return;
                }

                // 2. Obtener desde SQL el cliente dueño de la cuenta
                String codigoCliente = CuentaDAO.obtenerCodigoClientePorCuenta(conn, codigoCuenta);
                if (codigoCliente == null) {
                    JOptionPane.showMessageDialog(this,
                        "No se pudo obtener el dueño de la cuenta (Base de Datos).",
                        "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // 3. Realizar depósito (SQL incluido)
                boolean ok = banco.depositar(
                        codigoCliente,  // ← se obtuvo automáticamente
                        codigoCuenta,
                        monto,
                        null,           // empleado
                        "IGNORAR"       // el ID lo genera la BD
                );

                if (!ok) {
                    JOptionPane.showMessageDialog(this, "No se pudo realizar el depósito.");
                    return;
                }

                // 4. Obtener saldo actualizado
                double saldoActualizado = CuentaDAO.obtenerSaldo(conn, codigoCuenta);

                JOptionPane.showMessageDialog(this,
                        "Depósito realizado con éxito.\n" +
                        "Monto: S/. " + String.format("%.2f", monto) + "\n" +
                        "Nuevo saldo: S/. " + String.format("%.2f", saldoActualizado),
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);

                txtMonto.setText("");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Monto inválido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
