/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.*; 
/**
 *
 * @author Admin
 */
public class DepositoFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DepositoFrame.class.getName());

    /**
     * Creates new form DepositoFrame
     */
    private Banco banco;
    private Usuario usuario;

    public DepositoFrame(Banco banco, Usuario usuario) {
        initComponents();
        this.banco = banco;
        this.usuario = usuario;

        // Si el usuario es cliente, podríamos pre-llenar su cuenta automáticamente
        if (usuario instanceof UsuarioCliente) {
            UsuarioCliente uc = (UsuarioCliente) usuario;
            // Aquí podrías buscar la primera cuenta del cliente y ponerla en txtCuenta
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cuenta Destino");

        jLabel2.setText("Monto");

        txtMonto.addActionListener(this::txtMontoActionPerformed);

        jButton1.setText("Realizar Depósito");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCuenta)
                    .addComponent(txtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Obtener datos de los cuadros de texto
            String cta = txtCuenta.getText();
            double monto = Double.parseDouble(txtMonto.getText());
            String idTxn = "TXN" + System.currentTimeMillis();

            // 2. CORRECCIÓN: Buscar automáticamente el código del cliente dueño de la cuenta
            String codCliente = "";
            
            // Recorremos la lista de titulares del banco para encontrar de quién es la cuenta
            for(Titular t : banco.getListaTitular()){
                if(t.getCuenta().getCodigoCuenta().equals(cta)){
                    codCliente = t.getCliente().getCodigoCliente();
                    break; 
                }
            }

            // Si no encontramos dueño, detenemos la operación
            if(codCliente.isEmpty()) {
                 javax.swing.JOptionPane.showMessageDialog(this, "Cuenta no encontrada");
                 return;
            }

            // 3. Determinar el empleado (Si 'usuario' sigue en rojo, mira la nota abajo*)
            Empleado emp = null;
            if (usuario instanceof UsuarioEmpleado) {
                emp = ((UsuarioEmpleado) usuario).getEmpleado();
            }

            // 4. Realizar el depósito
            banco.depositar(codCliente, cta, monto, emp, idTxn);
            javax.swing.JOptionPane.showMessageDialog(this, "¡Depósito realizado con éxito!");

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El monto debe ser un número.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
