/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.*; 
/**
 *
 * @author Admin
 */
public class MenuEmpleadoFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuEmpleadoFrame.class.getName());

    /**
     * Creates new form MenuPrincipalFrame
     */
    private Banco banco;
    private GestorUsuarios gestor;
    private Usuario usuarioActual;

    public MenuEmpleadoFrame(Banco banco, GestorUsuarios gestor, Usuario usuario) {
        initComponents();
        this.banco = banco;
        this.gestor = gestor;
        this.usuarioActual = usuario;
        this.setTitle("Menu del Empleado");
        
        lblUsuario.setText("Hola, " + usuario.getNombreUsuario());
        aplicarPermisos(); // Método para ocultar botones según quién eres
    }

    private void aplicarPermisos() {
        // Si soy Cliente, no debo poder registrar nuevos clientes [cite: 6]
        if (usuarioActual instanceof UsuarioCliente) {
            btnRegCliente.setEnabled(false);
            btnRegCuenta.setEnabled(false);
        }
        // Si soy Empleado o Admin, tengo más permisos [cite: 5, 7]
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnRegCliente = new javax.swing.JButton();
        btnRegCuenta = new javax.swing.JButton();
        btnDeposito = new javax.swing.JButton();
        btnRetiro = new javax.swing.JButton();
        btnSaldo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnMovimientos = new javax.swing.JButton();
        btnMovimientos1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Bienvenido al Sistema Bancario");

        lblUsuario.setText("mostrar el nombre del usuario");

        btnRegCliente.setText("Registrar Cliente");
        btnRegCliente.addActionListener(this::btnRegClienteActionPerformed);

        btnRegCuenta.setText("Registrar Cuenta");
        btnRegCuenta.addActionListener(this::btnRegCuentaActionPerformed);

        btnDeposito.setText("Depósito");
        btnDeposito.addActionListener(this::btnDepositoActionPerformed);

        btnRetiro.setText("Retiro");
        btnRetiro.addActionListener(this::btnRetiroActionPerformed);

        btnSaldo.setText("Ver Saldo");
        btnSaldo.addActionListener(this::btnSaldoActionPerformed);

        btnSalir.setText("Cerrar Sesión");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        btnMovimientos.setText("Lista de clientes");
        btnMovimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMovimientos.setFocusPainted(false);
        btnMovimientos.addActionListener(this::btnListaClientesActionPerformed);

        btnMovimientos1.setText("Ver Movimientos");
        btnMovimientos1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMovimientos1.setFocusPainted(false);
        btnMovimientos1.addActionListener(this::btnMovimientosActionPerformed);

        jButton1.setText("Transferencia");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(btnSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRegCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRegCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMovimientos1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSalir)
                                        .addGap(17, 17, 17))
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(126, 126, 126))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetiro)
                    .addComponent(btnDeposito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMovimientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMovimientos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegClienteActionPerformed
        RegistrarClienteForm ventana = new RegistrarClienteForm(banco, gestor);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnRegClienteActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        new LoginFrame(banco, gestor).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoActionPerformed
        // TODO add your handling code here:
        DepositoFrame dep = new DepositoFrame(banco, usuarioActual);
        dep.setVisible(true);
        // No cerramos el menú (dispose) para que quede de fondo
    }//GEN-LAST:event_btnDepositoActionPerformed

    private void btnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroActionPerformed
        // TODO add your handling code here:
        RetiroFrame ret = new RetiroFrame(banco, usuarioActual); 
        ret.setVisible(true);
    }//GEN-LAST:event_btnRetiroActionPerformed

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        // TODO add your handling code here:
        ConsultaSaldoFrame consul= new ConsultaSaldoFrame(banco);
        consul.setVisible(true);
        
    }//GEN-LAST:event_btnSaldoActionPerformed

    private void btnListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaClientesActionPerformed
        ListaClientesFrame clientes = new ListaClientesFrame(banco, gestor);
        clientes.setVisible(true);
    }//GEN-LAST:event_btnListaClientesActionPerformed

    private void btnRegCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegCuentaActionPerformed
        RegistrarCuentaForm ventana = new RegistrarCuentaForm(banco);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnRegCuentaActionPerformed

    private void btnMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientosActionPerformed
        MovimientosFrame ventana = new MovimientosFrame(banco);
    
        // Hacerla visible
        ventana.setVisible(true);
    }//GEN-LAST:event_btnMovimientosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TransferenciaAdmYEmpFrame ventana = new TransferenciaAdmYEmpFrame(banco, usuarioActual);
        ventana.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeposito;
    private javax.swing.JButton btnMovimientos;
    private javax.swing.JButton btnMovimientos1;
    private javax.swing.JButton btnRegCliente;
    private javax.swing.JButton btnRegCuenta;
    private javax.swing.JButton btnRetiro;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
