/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
/**
 *
 * @author Admin
 */
public class MovimientosClienteFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MovimientosClienteFrame.class.getName());
    private Banco banco;
    private Usuario usuario;
    /**
     * Creates new form MovimientosFrame
     */
    public MovimientosClienteFrame(Banco banco, Usuario usuario) {
        initComponents();
        this.banco = banco;
        this.usuario = usuario;
        this.setLocationRelativeTo(null);
        this.setTitle("Historial de Movimientos");
        
        // Configurar columnas de la tabla manualmente si no lo hiciste en el diseñador
        DefaultTableModel modelo = (DefaultTableModel) tblMovimientos.getModel();
        modelo.setColumnIdentifiers(new String[] {"Fecha", "Hora", "Tipo", "Monto"});
        
        Cliente cliente = ((UsuarioCliente) usuario).getCliente();
        jComboBox1.removeAllItems();
        for (Titular t : banco.getListaTitular()) {
            if (t.getCliente().getCodigoCliente().equals(cliente.getCodigoCliente())) {
                jComboBox1.addItem(t.getCuenta().getCodigoCuenta());
            }
        }
    }
    // --- MÉTODO AUXILIAR PARA LLENAR LA TABLA ---
    private void cargarTabla(Cuenta cuenta) {
        // Obtenemos el "Modelo" de la tabla (es lo que controla los datos que se ven)
        DefaultTableModel modelo = (DefaultTableModel) tblMovimientos.getModel();

        // Paso 1: Limpiar la tabla por si tenía datos de otra búsqueda
        modelo.setRowCount(0);

        // Paso 2: Obtener el historial de la cuenta
        ArrayList<Transaccion> historial = cuenta.getHistorial();

        // Paso 3: Recorrer el historial y agregar filas
        for (Transaccion t : historial) {
            String tipo = determinarTipoTransaccion(t);

            // Agregamos una nueva fila a la tabla con los datos
            // NOTA: Asegúrate de tener el método getMonto() en Transaccion.java
            modelo.addRow(new Object[]{
                t.getFechaFormateada(),
                t.getHoraFormateada(),
                tipo,
                "S/. " + t.getMonto() 
            });
        }

        if (historial.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Esta cuenta no tiene movimientos registrados.");
        }
    }

    private void limpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblMovimientos.getModel();
        modelo.setRowCount(0);
    }

    // Método para saber qué texto poner en la columna "Tipo"
    private String determinarTipoTransaccion(Transaccion t) {
        if (t instanceof Deposito) return "Depósito";
        if (t instanceof Retiro) return "Retiro";
        if (t instanceof Transferencia) return "Transferencia";
        return "Desconocido";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovimientos = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnBuscar.setText("Ver Historial");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        tblMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Hora", "Tipo", "Monto"
            }
        ));
        jScrollPane1.setViewportView(tblMovimientos);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Tus Cuentas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String codigoCuenta = (String) jComboBox1.getSelectedItem();

        if (codigoCuenta == null || codigoCuenta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione una cuenta.");
            return;
        }

        Cuenta cuentaEncontrada = banco.buscarCuenta(codigoCuenta);

        if (cuentaEncontrada != null) {
            cargarTabla(cuentaEncontrada);
        } else {
            JOptionPane.showMessageDialog(this, "La cuenta " + codigoCuenta + " no existe.");
            limpiarTabla();
        }  
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMovimientos;
    // End of variables declaration//GEN-END:variables

}