/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.*; // Importar las clases lógicas
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class RegistrarCuentaForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrarCuentaForm.class.getName());
    private Banco banco;
    /**
     * Creates new form RegistrarCuentaForm
     */
    public RegistrarCuentaForm(Banco banco) {
        initComponents();
        this.banco = banco;
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Solo cerrar esta ventana
        this.setLocationRelativeTo(null); // Centrar
        this.setTitle("Crear Nueva Cuenta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo de Cuenta");

        jLabel2.setText("DNI");

        jLabel3.setText("Saldo Inicial");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton1.setText("Crear Cuenta");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3))
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. OBTENER DATOS
        String codCuenta = jTextField1.getText().trim();
        String dniCliente = jTextField2.getText().trim();
        String saldoStr = jTextField3.getText().trim();

        // ==========================================================
        // 2. VALIDACIONES USANDO TU ARCHIVO "Validaciones.java"
        // ==========================================================
        
        // A) Validar que los campos no estén vacíos (usando validarTexto)
        if (!Validaciones.validarTexto(codCuenta) || !Validaciones.validarTexto(dniCliente)) {
             javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete los campos obligatorios.");
             return;
        }

        // B) Validar el formato del Código de Cuenta (Debe ser CTA + números)
        // Revisa tu archivo Validaciones.java, método validarCodigoCuenta
        if (!Validaciones.validarCodigoCuenta(codCuenta)) {
             javax.swing.JOptionPane.showMessageDialog(this, 
                 "Código de Cuenta inválido.\n" + Validaciones.obtenerMensajeError("codigo_cuenta"));
             return;
        }

        // C) Validar formato del DNI (8 dígitos)
        // Revisa tu archivo Validaciones.java, método validarDNI
        if (!Validaciones.validarDNI(dniCliente)) {
             javax.swing.JOptionPane.showMessageDialog(this, 
                 "DNI inválido.\n" + Validaciones.obtenerMensajeError("dni"));
             return;
        }

        // ==========================================================
        // 3. LÓGICA DE NEGOCIO (BUSCAR Y CREAR)
        // ==========================================================
        try {
            // Verificar si la cuenta ya existe en el banco
            if (banco.buscarCuenta(codCuenta) != null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: Ya existe una cuenta con ese código.");
                return;
            }

            // Buscar al dueño usando el DNI validado
            Cliente dueno = null;
            // Recorremos la lista para buscar por DNI
            for (Cliente c : banco.getListaClientes()) {
                if (c.getDni().equals(dniCliente)) {
                    dueno = c;
                    break;
                }
            }

            // Si no encontramos al cliente
            if (dueno == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún cliente con el DNI: " + dniCliente);
                return;
            }

            // Crear la cuenta
            banco.crearCuenta(codCuenta, dueno);

            // Asignar Saldo Inicial (Opcional) con validación básica
            if (!saldoStr.isEmpty()) {
                try {
                    double saldo = Double.parseDouble(saldoStr);
                    if (saldo < 0) {
                         javax.swing.JOptionPane.showMessageDialog(this, "El saldo inicial no puede ser negativo.");
                         return; // No cerramos ventana para que corrija
                    }
                    Cuenta nuevaCuenta = banco.buscarCuenta(codCuenta);
                    if(nuevaCuenta != null) nuevaCuenta.setSaldo(saldo);
                    
                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "El saldo debe ser un número válido.");
                    return;
                }
            }

            // Éxito
            javax.swing.JOptionPane.showMessageDialog(this, "¡Cuenta creada exitosamente para " + dueno.getNombre() + "!");
            this.dispose(); // Cerrar ventana

        } catch (Exception e) {
             javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
