/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.*;
import javax.swing.JOptionPane;
import BaseDatos.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
/**
 *
 * @author Admin
 */
public class RetiroClienteFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RetiroClienteFrame.class.getName());

    /**
     * Creates new form RetiroFrame
     */
    private Banco banco;
    private Usuario usuario;

    public RetiroClienteFrame(Banco banco, Usuario usuario) {
        initComponents();
        this.banco = banco;
        this.usuario = usuario;
        this.setTitle("Retiro");
        setLocationRelativeTo(null);
        if (usuario instanceof UsuarioCliente) {
            Cliente cliente = ((UsuarioCliente) usuario).getCliente();
            jComboBox1.removeAllItems();
            
            // Obtener cuentas del cliente desde la BD
            java.util.List<Cuenta> cuentasCliente = banco.buscarCuentasDeCliente(cliente.getCodigoCliente());
            
            if (cuentasCliente.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No tienes cuentas registradas.");
            } else {
                for (Cuenta cuenta : cuentasCliente) {
                    jComboBox1.addItem(cuenta.getCodigoCuenta());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtMonto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 170, -1));

        txtMonto.setBackground(new java.awt.Color(204, 204, 204));
        txtMonto.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(0, 0, 0));
        txtMonto.addActionListener(this::txtMontoActionPerformed);
        jPanel1.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 170, -1));

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tus Cuentas:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 103, -1));

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Monto a retirar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 130, -1));

        jButton1.setBackground(new java.awt.Color(239, 184, 16));
        jButton1.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Realizar Retiro");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try (Connection conn = Conexion.conectar()) {

            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Error al conectar a la base de datos.");
                return;
            }

            // 1. Leer monto
            String montoTexto = txtMonto.getText().trim();
            if (montoTexto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese un monto.");
                return;
            }

            double monto = Double.parseDouble(montoTexto);

            // 2. Obtener cuenta seleccionada
            String codCuenta = (String) jComboBox1.getSelectedItem();
            if (codCuenta == null || codCuenta.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Seleccione una cuenta.");
                return;
            }

            // 3. Obtener código del cliente usando la conexión
            String codCliente = CuentaDAO.obtenerCodigoClientePorCuenta(conn, codCuenta);
            if (codCliente == null) {
                JOptionPane.showMessageDialog(this, "No se pudo obtener el dueño de la cuenta.");
                return;
            }

            // 4. Realizar el retiro usando BANCO (pasa la conexión)
            boolean exito = banco.retirar(conn, codCliente, codCuenta, monto, null, null);

            if (!exito) {
                JOptionPane.showMessageDialog(this,
                    "No se pudo realizar el retiro.\n" +
                    "Verifique los datos o saldo insuficiente.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 5. Obtener saldo actualizado desde SQL
            double saldoActual = CuentaDAO.obtenerSaldo(conn, codCuenta);

            JOptionPane.showMessageDialog(this,
                    "Retiro realizado con éxito.\n" +
                    "Saldo restante: S/. " + String.format("%.2f", saldoActual),
                    "Muchas Gracias",
                    JOptionPane.INFORMATION_MESSAGE);

            txtMonto.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Ingrese un monto válido.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
