/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.*; 
import javax.swing.JOptionPane;
import java.util.ArrayList;
/**
 *
 * @author Admin
 */
public class TransferenciaClienteFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransferenciaClienteFrame.class.getName());
    private Banco banco;
    private UsuarioCliente usuarioCliente;
    // Lista auxiliar para guardar las cuentas reales y no solo el texto del combo
    private ArrayList<Cuenta> misCuentas;
    /**
     * Creates new form TransferenciaCliente
     */
    public TransferenciaClienteFrame(Banco banco, Usuario usuario) {
        initComponents();
        this.banco = banco;
        
        // Validamos que sea un cliente (por seguridad)
        if (usuario instanceof UsuarioCliente) {
            this.usuarioCliente = (UsuarioCliente) usuario;
        }
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setTitle("Transferencia - " + usuario.getNombreUsuario());
        
        cargarCuentasEnCombo();
    }
    private void cargarCuentasEnCombo() {
        cmbCuentasOrigen.removeAllItems(); // Limpiar
        
        // 1. Obtener el código del cliente logueado
        String codigoCliente = usuarioCliente.getCliente().getCodigoCliente();
        
        // 2. Buscar sus cuentas en el banco
        misCuentas = banco.buscarCuentasDeCliente(codigoCliente);
        
        // 3. Llenar el combo visualmente
        if (misCuentas.isEmpty()) {
            cmbCuentasOrigen.addItem("No tienes cuentas registradas");
            btnTransferir.setEnabled(false);
        } else {
            for (Cuenta c : misCuentas) {
                // Mostramos Código y Saldo para ayudar al usuario
                cmbCuentasOrigen.addItem(c.getCodigoCuenta() + " (Saldo: S/." + c.getSaldo() + ")");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbCuentasOrigen = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        btnTransferir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cuenta de Origen");

        cmbCuentasOrigen.addActionListener(this::cmbCuentasOrigenActionPerformed);

        jLabel2.setText("Tus cuentas");

        jLabel3.setText("Cuenta de Destino");

        txtDestino.addActionListener(this::txtDestinoActionPerformed);

        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(this::btnTransferirActionPerformed);

        jLabel4.setText("Monto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbCuentasOrigen, 0, 176, Short.MAX_VALUE)
                    .addComponent(txtDestino)
                    .addComponent(txtMonto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTransferir)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCuentasOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addComponent(btnTransferir)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Validar selección de cuenta origen
            int indiceSeleccionado = cmbCuentasOrigen.getSelectedIndex();
            if (indiceSeleccionado < 0 || misCuentas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor selecciona una cuenta de origen.");
                return;
            }
            
            // Obtenemos el objeto Cuenta real usando la lista auxiliar y el índice
            Cuenta cuentaOrigen = misCuentas.get(indiceSeleccionado);
            
            // 2. Obtener y Validar datos de destino
            String ctaDestino = txtDestino.getText().trim();
            String montoStr = txtMonto.getText().trim();
            
            if (ctaDestino.isEmpty() || montoStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Complete todos los campos.");
                return;
            }
            
            // Validar que no se transfiera a sí mismo (misma cuenta)
            if (cuentaOrigen.getCodigoCuenta().equalsIgnoreCase(ctaDestino)) {
                JOptionPane.showMessageDialog(this, "No puedes transferir a la misma cuenta de origen.");
                return;
            }

            // 3. Validar Monto y Saldo
            double monto = Double.parseDouble(montoStr);
            if (monto <= 0) {
                JOptionPane.showMessageDialog(this, "El monto debe ser mayor a 0.");
                return;
            }
            
            // VERIFICACIÓN DE SALDO (Lo que pediste)
            if (cuentaOrigen.getSaldo() < monto) {
                JOptionPane.showMessageDialog(this, "Saldo insuficiente.\n" +
                        "Tu saldo actual es: S/." + cuentaOrigen.getSaldo());
                return;
            }

            // 4. Ejecutar Transferencia en el Banco
            String idTxn = "TXN" + System.currentTimeMillis();
            String codCliente = usuarioCliente.getCliente().getCodigoCliente();
            
            // Llamamos al método transferir del Banco
            // Nota: Pasamos 'null' en empleado porque lo hace el cliente directo
            Transaccion resultado = banco.transferir(codCliente, cuentaOrigen.getCodigoCuenta(), ctaDestino, monto, null, idTxn);
            
            if (resultado != null) {
                JOptionPane.showMessageDialog(this, "¡Transferencia Exitosa!\n" +
                        "Nuevo Saldo: S/." + cuentaOrigen.getSaldo());
                
                // Actualizar el combo para reflejar el nuevo saldo
                cargarCuentasEnCombo();
                // Seleccionar de nuevo la cuenta que se usó
                cmbCuentasOrigen.setSelectedIndex(indiceSeleccionado);
                
                // Limpiar campos
                txtDestino.setText("");
                txtMonto.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Error: Verifique que la cuenta destino exista.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un monto válido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void txtDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinoActionPerformed

    private void cmbCuentasOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCuentasOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCuentasOrigenActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferir;
    private javax.swing.JComboBox<String> cmbCuentasOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
