/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import modelo.*; 
import javax.swing.JOptionPane;
import java.util.ArrayList;
import BaseDatos.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
/**
 *
 * @author Admin
 */
public class TransferenciaClienteFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransferenciaClienteFrame.class.getName());
    private Banco banco;
    private UsuarioCliente usuario;
    // Lista auxiliar para guardar las cuentas reales y no solo el texto del combo
    private ArrayList<Cuenta> misCuentas;
    /**
     * Creates new form TransferenciaCliente
     */
    public TransferenciaClienteFrame(Banco banco, Usuario usuario) {
        initComponents();
        this.banco = banco;
        
        // Validamos que sea un cliente (por seguridad)
        if (usuario instanceof UsuarioCliente) {
            this.usuario = (UsuarioCliente) usuario;
        }
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setTitle("Transferencia - " + usuario.getNombreUsuario());
        
        cargarCuentasEnCombo();
    }
    private void cargarCuentasEnCombo() {
    if (usuario instanceof UsuarioCliente) {
                Cliente cliente = ((UsuarioCliente) usuario).getCliente();
                cmbCuentasOrigen.removeAllItems();

                // Obtener cuentas del cliente desde la BD
                java.util.List<Cuenta> cuentasCliente = banco.buscarCuentasDeCliente(cliente.getCodigoCliente());

                if (cuentasCliente.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No tienes cuentas registradas.");
                } else {
                    for (Cuenta cuenta : cuentasCliente) {
                        cmbCuentasOrigen.addItem(cuenta.getCodigoCuenta());
                    }
                }
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCuentasOrigen = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnTransferir = new javax.swing.JButton();
        txtMonto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbCuentasOrigen.setBackground(new java.awt.Color(204, 204, 204));
        cmbCuentasOrigen.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        cmbCuentasOrigen.setForeground(new java.awt.Color(0, 0, 0));
        cmbCuentasOrigen.addActionListener(this::cmbCuentasOrigenActionPerformed);
        getContentPane().add(cmbCuentasOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 176, -1));

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cuenta de Destino:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, -1));

        txtDestino.setBackground(new java.awt.Color(204, 204, 204));
        txtDestino.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtDestino.setForeground(new java.awt.Color(0, 0, 0));
        txtDestino.addActionListener(this::txtDestinoActionPerformed);
        getContentPane().add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 176, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTransferir.setBackground(new java.awt.Color(239, 184, 16));
        btnTransferir.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        btnTransferir.setForeground(new java.awt.Color(0, 0, 0));
        btnTransferir.setText("Transferir");
        btnTransferir.setBorderPainted(false);
        btnTransferir.addActionListener(this::btnTransferirActionPerformed);
        jPanel1.add(btnTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        txtMonto.setBackground(new java.awt.Color(204, 204, 204));
        txtMonto.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 176, -1));

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Monto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 107, -1));

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cuenta de Origen:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        // TODO add your handling code here:
   
        try {
            // 1. Obtener cuenta origen del combo
            String codigoCuentaOrigen = (String) cmbCuentasOrigen.getSelectedItem();
            if (codigoCuentaOrigen == null || codigoCuentaOrigen.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Seleccione una cuenta de origen.");
                return;
            }

            // 2. Obtener datos de destino
            String codigoCuentaDestino = txtDestino.getText().trim();
            String montoStr = txtMonto.getText().trim();

            if (codigoCuentaDestino.isEmpty() || montoStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Complete todos los campos.");
                return;
            }

            // Validar monto
            double monto = Double.parseDouble(montoStr);
            if (monto <= 0) {
                JOptionPane.showMessageDialog(this, "El monto debe ser mayor a 0.");
                return;
            }

            // 3. Obtener saldo actual de la cuenta origen
            double saldoOrigen = CuentaDAO.obtenerSaldo(null,codigoCuentaOrigen);
            if (saldoOrigen < monto) {
                JOptionPane.showMessageDialog(this, "Saldo insuficiente.\nSaldo actual: S/." + saldoOrigen);
                return;
            }

            // 4. Abrir conexión y desactivar auto-commit para la transacción
            Connection conn = Conexion.conectar();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos.");
                return;
            }
            conn.setAutoCommit(false);

            try {
                // 5. Actualizar saldos en SQL
                boolean okOrigen = CuentaDAO.actualizarSaldo(conn, codigoCuentaOrigen, saldoOrigen - monto);
                double saldoDestino = CuentaDAO.obtenerSaldo(conn, codigoCuentaDestino);
                boolean okDestino = CuentaDAO.actualizarSaldo(conn, codigoCuentaDestino, saldoDestino + monto);

                if (!okOrigen || !okDestino) {
                    conn.rollback();
                    JOptionPane.showMessageDialog(this, "Error al actualizar saldos. Transacción cancelada.");
                    return;
                }

                // 6. Registrar transacción en SQL
                boolean tx = TransaccionDAO.insertarTransaccion(conn, codigoCuentaOrigen, codigoCuentaDestino, null, monto, "transferencia");
                if (!tx) {
                    conn.rollback();
                    JOptionPane.showMessageDialog(this, "Error al registrar la transacción. Transacción cancelada.");
                    return;
                }

                // 7. Confirmar todo
                conn.commit();
                JOptionPane.showMessageDialog(this, "¡Transferencia exitosa!");

                // 8. Limpiar campos
                txtDestino.setText("");
                txtMonto.setText("");

            } catch (SQLException ex) {
                conn.rollback();
                JOptionPane.showMessageDialog(this, "Error en la transferencia: " + ex.getMessage());
            } finally {
                conn.setAutoCommit(true);
                conn.close();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un monto válido.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void txtDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinoActionPerformed

    private void cmbCuentasOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCuentasOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCuentasOrigenActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferir;
    private javax.swing.JComboBox<String> cmbCuentasOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
