/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.*; // Importamos la lógica del negocio
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class TransferenciaAdmYEmpFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransferenciaAdmYEmpFrame.class.getName());
    private Banco banco;
    private Usuario usuario;
    /**
     * Creates new form TransferenciaAdmYEmp
     */
    public TransferenciaAdmYEmpFrame(Banco banco, Usuario usuario) {
        initComponents();
        this.banco = banco;
        this.usuario = usuario;
        
        // Configuración de ventana
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Solo cerrar esta ventana
        this.setLocationRelativeTo(null); // Centrar en pantalla
        this.setTitle("Transferencia entre Cuentas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        btnTransferir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cuenta de Origen");

        jLabel2.setText("Cuenta de Destino");

        txtOrigen.addActionListener(this::txtOrigenActionPerformed);

        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(this::btnTransferirActionPerformed);

        jLabel3.setText("Monto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(txtOrigen)
                    .addComponent(txtDestino))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnTransferir)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Obtener datos
            String ctaOrigen = txtOrigen.getText().trim();
            String ctaDestino = txtDestino.getText().trim();
            String montoStr = txtMonto.getText().trim();
            
            // 2. Validaciones básicas de campos vacíos
            if(ctaOrigen.isEmpty() || ctaDestino.isEmpty() || montoStr.isEmpty()){
                JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.");
                return;
            }
            
            // 3. Validar que las cuentas sean diferentes (Validaciones.java lo hace, pero aquí es bueno avisar rápido)
            if(ctaOrigen.equals(ctaDestino)){
                JOptionPane.showMessageDialog(this, "La cuenta de origen y destino no pueden ser la misma.");
                return;
            }

            double monto = Double.parseDouble(montoStr);
            String idTxn = "TXN" + System.currentTimeMillis();

            // 4. BUSCAR EL CLIENTE DUEÑO DE LA CUENTA ORIGEN
            // El método banco.transferir() pide el código del cliente origen.
            // Como el empleado solo escribió la cuenta, debemos buscar de quién es.
            String codClienteOrigen = "";
            
            for(Titular t : banco.getListaTitular()){
                if(t.getCuenta().getCodigoCuenta().equals(ctaOrigen)){
                    codClienteOrigen = t.getCliente().getCodigoCliente();
                    break;
                }
            }
            
            if(codClienteOrigen.isEmpty()){
                JOptionPane.showMessageDialog(this, "La cuenta de origen no existe o no tiene titular asignado.");
                return;
            }

            // 5. Identificar al Empleado que realiza la operación
            Empleado empResponsable = null;
            if (usuario instanceof UsuarioEmpleado) {
                empResponsable = ((UsuarioEmpleado) usuario).getEmpleado();
            } 
            // Si es admin, también podría tener un empleado asociado, o se pasa null si la lógica lo permite.
            else if (usuario instanceof UsuarioAdministrador) {
                empResponsable = ((UsuarioAdministrador) usuario).getAdministrador();
            }

            // 6. EJECUTAR TRANSFERENCIA
            // Usamos el método transferir de la clase Banco
            Transaccion resultado = banco.transferir(codClienteOrigen, ctaOrigen, ctaDestino, monto, empResponsable, idTxn);
            
            if (resultado != null) {
                JOptionPane.showMessageDialog(this, "¡Transferencia realizada con éxito!");
                
                // Opcional: Mostrar nuevos saldos si deseas buscar las cuentas y mostrarlos
                this.dispose(); // Cerrar ventana
            } else {
                // Si devuelve null, es porque falló alguna validación interna (fondos insuficientes, cuenta destino no existe, etc.)
                JOptionPane.showMessageDialog(this, "Error en la transferencia.\nVerifique que la cuenta destino exista y que el saldo sea suficiente.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El monto debe ser un número válido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void txtOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrigenActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
