/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.*; // Importamos la lógica del negocio
import javax.swing.JOptionPane;
import BaseDatos.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
/**
 *
 * @author Admin
 */
public class TransferenciaAdmYEmpFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransferenciaAdmYEmpFrame.class.getName());
    private Banco banco;
    private Usuario usuario;
    /**
     * Creates new form TransferenciaAdmYEmp
     */
    public TransferenciaAdmYEmpFrame(Banco banco, Usuario usuario) {
        initComponents();
        this.banco = banco;
        this.usuario = usuario;
        
        // Configuración de ventana
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Solo cerrar esta ventana
        this.setLocationRelativeTo(null); // Centrar en pantalla
        this.setTitle("Transferencia entre Cuentas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnTransferir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cuenta de Origen:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtOrigen.setBackground(new java.awt.Color(204, 204, 204));
        txtOrigen.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtOrigen.setForeground(new java.awt.Color(0, 0, 0));
        txtOrigen.addActionListener(this::txtOrigenActionPerformed);
        jPanel1.add(txtOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 160, -1));

        txtDestino.setBackground(new java.awt.Color(204, 204, 204));
        txtDestino.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtDestino.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 160, -1));

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cuenta de Destino:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Monto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txtMonto.setBackground(new java.awt.Color(204, 204, 204));
        txtMonto.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 160, -1));

        btnTransferir.setBackground(new java.awt.Color(239, 184, 16));
        btnTransferir.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        btnTransferir.setForeground(new java.awt.Color(0, 0, 0));
        btnTransferir.setText("Transferir");
        btnTransferir.setBorderPainted(false);
        btnTransferir.addActionListener(this::btnTransferirActionPerformed);
        jPanel1.add(btnTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        // TODO add your handling code here:
        try (Connection conn = Conexion.conectar()) {
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos.");
                return;
            }

            conn.setAutoCommit(false); // inicio de transacción

            // 1. Leer datos
            String ctaOrigen = txtOrigen.getText().trim();
            String ctaDestino = txtDestino.getText().trim();
            String montoStr = txtMonto.getText().trim();

            if(ctaOrigen.isEmpty() || ctaDestino.isEmpty() || montoStr.isEmpty()){
                JOptionPane.showMessageDialog(this, "Complete todos los campos.");
                return;
            }

            if(ctaOrigen.equals(ctaDestino)){
                JOptionPane.showMessageDialog(this, "La cuenta de origen y destino no pueden ser la misma.");
                return;
            }

            double monto = Double.parseDouble(montoStr);

            // 2. Obtener código del cliente usando la misma conexión
            String codCliente = CuentaDAO.obtenerCodigoClientePorCuenta(conn, ctaOrigen);
            if(codCliente == null){
                JOptionPane.showMessageDialog(this, "La cuenta origen no existe o no tiene cliente asignado.");
                return;
            }

            try {
                // 3. Obtener saldos
                Double saldoOrigen = CuentaDAO.obtenerSaldo(conn, ctaOrigen);
                if(saldoOrigen == null){
                    JOptionPane.showMessageDialog(this, "No se pudo obtener el saldo de la cuenta origen.");
                    conn.rollback();
                    return;
                }

                Double saldoDestino = CuentaDAO.obtenerSaldo(conn, ctaDestino);
                if(saldoDestino == null){
                    JOptionPane.showMessageDialog(this, "La cuenta destino no existe.");
                    conn.rollback();
                    return;
                }

                if(saldoOrigen < monto){
                    JOptionPane.showMessageDialog(this, "Saldo insuficiente en la cuenta origen.");
                    conn.rollback();
                    return;
                }

                // 4. Actualizar saldos
                CuentaDAO.actualizarSaldo(conn, ctaOrigen, saldoOrigen - monto);
                CuentaDAO.actualizarSaldo(conn, ctaDestino, saldoDestino + monto);

                // 5. Registrar transacción
                TransaccionDAO.insertarTransaccion(conn, ctaOrigen, ctaDestino, null, monto, "transferencia");

                // 6. Commit
                conn.commit();
                JOptionPane.showMessageDialog(this, "¡Transferencia realizada con éxito!");

                // Limpiar campos
                txtOrigen.setText("");
                txtDestino.setText("");
                txtMonto.setText("");

            } catch (SQLException e){
                conn.rollback();
                JOptionPane.showMessageDialog(this, "Error en la transferencia: " + e.getMessage());
            }

        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El monto debe ser un número válido.");
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void txtOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrigenActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
